//SPDX-License-Identifier: MIT
pragma solidity >=0.8.23 <0.9.0;

import "./interfaces/ISemaphore.sol";
import "./interfaces/IZKPassportVerifier.sol";

contract UniPassRegistry {
    ISemaphore public immutable semaphore;
    IZKPassportVerifier public immutable zkPassportVerifier;
    uint256 public immutable uniPassGroupId;
    
    // The domain and scope used for ZKPassport verification
    string public constant ZK_APP_DOMAIN = "unipass.id";
    string public constant ZK_APP_SCOPE = "unipass-registry";

    // Mapping to store consumed nullifiers from Semaphore proofs (Scope-Specific User Actions)
    mapping(uint256 => bool) public nullifiers;

    // Mapping to store consumed passport identifiers (Global Identity Registration)
    mapping(bytes32 => bool) public passportIdentifiers;

    event UserRegistered(uint256 indexed identityCommitment, bytes32 indexed passportId);
    event ProofVerified(uint256 indexed nullifier, uint256 indexed scope);

    constructor(address _semaphoreAddress, address _zkPassportVerifierAddress) {
        semaphore = ISemaphore(_semaphoreAddress);
        zkPassportVerifier = IZKPassportVerifier(_zkPassportVerifierAddress);
        
        // Create a new group managed by this contract
        uniPassGroupId = semaphore.createGroup(address(this));
    }

    /**
     * @dev Registers a user by verifying their passport proof and adding their Semaphore identity.
     * @param identityCommitment The user's Semaphore identity commitment.
     * @param passportProof The ZK proof parameters from ZKPassport.
     * @param isIDCard Whether the document is an ID card (affects data decoding).
     */
    function register(
        uint256 identityCommitment, 
        ProofVerificationParams calldata passportProof,
        bool isIDCard
    ) external {
        // 1. Verify Passport Proof
        (bool verified, bytes32 uniqueIdentifier, IZKPassportHelper helper) = zkPassportVerifier.verify(passportProof);
        require(verified, "Invalid Passport Proof");

        // 2. Verify Scope and Domain (Security Check)
        require(
            helper.verifyScopes(passportProof.proofVerificationData.publicInputs, ZK_APP_DOMAIN, ZK_APP_SCOPE),
            "Invalid Scope or Domain"
        );

        // 3. Verify Sender Binding (Prevent Front-running)
        BoundData memory boundData = helper.getBoundData(passportProof.committedInputs);
        require(boundData.senderAddress == msg.sender, "Proof bound to different address");
        require(boundData.chainId == block.chainid, "Proof bound to different chain");

        // 4. Check Passport Uniqueness (Prevent same passport registering twice)
        require(!passportIdentifiers[uniqueIdentifier], "Passport already registered");
        passportIdentifiers[uniqueIdentifier] = true;

        // 5. Add to Semaphore Group
        semaphore.addMember(uniPassGroupId, identityCommitment);

        emit UserRegistered(identityCommitment, uniqueIdentifier);
    }

    /**
     * @dev Verifies a user's action within a specific scope (DApp).
     *      Consumes the nullifier to prevent double-action in that scope.
     *      This is a helper for DApps that don't want to interact with Semaphore directly.
     * @param proof The Semaphore proof generated by the user.
     */
    function verifyAndConsume(ISemaphore.SemaphoreProof calldata proof) external {
        // 1. Check if nullifier is already used
        require(!nullifiers[proof.nullifier], "Nullifier already used");

        // 2. Verify the proof via Semaphore
        // We verify that the user is a member of uniPassGroupId
        bool isValid = semaphore.verifyProof(uniPassGroupId, proof);
        require(isValid, "Invalid Semaphore Proof");

        // 3. Mark nullifier as used
        nullifiers[proof.nullifier] = true;

        emit ProofVerified(proof.nullifier, proof.scope);
    }
    
    /**
     * @dev Returns the group ID for DApps to use
     */
    function getGroupId() external view returns (uint256) {
        return uniPassGroupId;
    }
}
