//SPDX-License-Identifier: MIT
pragma solidity >=0.8.23 <0.9.0;

import "./interfaces/ISemaphore.sol";
import "./interfaces/IZKPassportVerifier.sol";

contract UniPassRegistry {
    ISemaphore public immutable semaphore;
    IZKPassportVerifier public immutable zkPassportVerifier;
    uint256 public immutable uniPassGroupId;

    // Mapping to store consumed nullifiers from Semaphore proofs (Scope-Specific User Actions)
    mapping(uint256 => bool) public nullifiers;

    // Mapping to store consumed passport nullifiers (Global Identity Registration)
    mapping(uint256 => bool) public passportNullifiers;

    event UserRegistered(uint256 indexed identityCommitment);
    event ProofVerified(uint256 indexed nullifier, uint256 indexed scope);

    constructor(address _semaphoreAddress, address _zkPassportVerifierAddress) {
        semaphore = ISemaphore(_semaphoreAddress);
        zkPassportVerifier = IZKPassportVerifier(_zkPassportVerifierAddress);
        
        // Create a new group managed by this contract
        uniPassGroupId = semaphore.createGroup(address(this));
    }

    /**
     * @dev Registers a user by verifying their passport proof and adding their Semaphore identity.
     * @param identityCommitment The user's Semaphore identity commitment.
     * @param passportProof The ZK proof showing they hold a valid passport.
     */
    function register(
        uint256 identityCommitment, 
        IZKPassportVerifier.PassportProof calldata passportProof
    ) external {
        // 1. Verify Passport Proof (In reality, checks ZK proof of signature)
        require(zkPassportVerifier.verifyPassport(passportProof), "Invalid Passport Proof");

        // 2. Check Passport Nullifier (Prevent same passport registering twice)
        require(!passportNullifiers[passportProof.nullifier], "Passport already registered");
        passportNullifiers[passportProof.nullifier] = true;

        // 3. Add to Semaphore Group
        semaphore.addMember(uniPassGroupId, identityCommitment);

        emit UserRegistered(identityCommitment);
    }

    /**
     * @dev Verifies a user's action within a specific scope (DApp).
     *      Consumes the nullifier to prevent double-action in that scope.
     * @param proof The Semaphore proof generated by the user.
     */
    function verifyAndConsume(ISemaphore.SemaphoreProof calldata proof) external {
        // 1. Check if nullifier is already used
        require(!nullifiers[proof.nullifier], "Nullifier already used");

        // 2. Verify the proof via Semaphore
        // The 'scope' in the proof acts as the external nullifier (e.g., DApp address or Campaign ID)
        // The 'message' can be any signal (e.g., user address, vote choice)
        
        // Note: validateProof in Semaphore usually stores the nullifier inside the Semaphore contract itself.
        // However, Semaphore v4 might store it per group. 
        // If we want a shared anonymity set but distinct scopes, we should manage nullifiers here 
        // OR use different external nullifiers with Semaphore's validation.
        // Let's call verifyProof (view) and manage storage here to allow infinite scopes for one group.
        
        bool isValid = semaphore.verifyProof(uniPassGroupId, proof);
        require(isValid, "Invalid Semaphore Proof");

        // 3. Mark nullifier as used
        nullifiers[proof.nullifier] = true;

        emit ProofVerified(proof.nullifier, proof.scope);
    }
}

